- name: Configure Files
  hosts:
    - headnode
  become: true
  tasks:
    - name: Copy /etc/hostname
      ansible.builtin.copy:
        force: false
        src: ../etc/hostname
        dest: /etc/hostname
    
    - name: Create directory /sharedfs
      ansible.builtin.file:
        path: /sharedfs
        state: directory
        owner: nobody
        group: nogroup
        mode: u=rwx,g=rxx,o=rwx
